### ISSUE TITLE
PHP7 deprecated constructor notices

### ISSUE THREAD

**Issue by lkraav** [hull/hull-php#8]
Heya. Please start using `__construct()` or you will spam the hell out debug logs.

http://php.net/manual/en/migration70.deprecated.php

**Comment by michaloo** [comment]
Thanks for reporting that @lkraav, we will soon resolve the issue.

**Comment by michaloo** [comment]
Done here: https://github.com/hull/hull-php/pull/9

Thanks for the patience @lkraav
